enabled: true
production-mode: true
grid-size: grid-xl
layout-list-blog: true
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
header-showexternallinks: false
header-externallinks:
  -
    icon: 'fa fa-newspaper-o'
    text: Blog
    url: /blog
    target: false
  -
    icon: 'fa fa-github'
    text: GitHub
    url: 'https://github.com/gamecult'
    target: true
analytics_id: null
custom_logo:
  'user/themes/klb4/images/logo/Gamecult logo.svg':
    name: 'Gamecult logo.svg'
    type: image/svg+xml
    size: 7149
    path: 'user/themes/klb4/images/logo/Gamecult logo.svg'
custom_logo_mobile:
  'user/themes/klb4/images/logo/Gamecult logo.svg':
    name: 'Gamecult logo.svg'
    type: image/svg+xml
    size: 7149
    path: 'user/themes/klb4/images/logo/Gamecult logo.svg'
